# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: queue_ding 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "queue_ding"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Fred Mitchell"]
  s.date = "2016-10-23"
  s.description = "\n  This roughly mirrors the functionaly of Queue in allowing you to\n  queue messages to one or more threads, and will block if the queue\n  is empty, waking up when there is another message available.\n  "
  s.email = "fred.mitchell@gmx.de"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".semver",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/queue_ding.rb",
    "lib/queue_ding/queue_ding.rb",
    "queue_ding.gemspec",
    "spec/queue_ding_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/flajann2/queue_ding"
  s.licenses = ["MIT"]
  s.required_ruby_version = Gem::Requirement.new(">= 2.2.2")
  s.rubygems_version = "2.5.1"
  s.summary = "QueueDing is a working alternative to Queue"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aquarium>, ["~> 0"])
      s.add_runtime_dependency(%q<semver>, ["~> 1"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<yard>, ["~> 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3"])
      s.add_development_dependency(%q<bundler>, ["~> 1"])
      s.add_development_dependency(%q<juwelier>, ["~> 2"])
      s.add_development_dependency(%q<simplecov>, ["~> 0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 0"])
    else
      s.add_dependency(%q<aquarium>, ["~> 0"])
      s.add_dependency(%q<semver>, ["~> 1"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<yard>, ["~> 0"])
      s.add_dependency(%q<rdoc>, ["~> 3"])
      s.add_dependency(%q<bundler>, ["~> 1"])
      s.add_dependency(%q<juwelier>, ["~> 2"])
      s.add_dependency(%q<simplecov>, ["~> 0"])
      s.add_dependency(%q<guard-rspec>, ["~> 0"])
    end
  else
    s.add_dependency(%q<aquarium>, ["~> 0"])
    s.add_dependency(%q<semver>, ["~> 1"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<yard>, ["~> 0"])
    s.add_dependency(%q<rdoc>, ["~> 3"])
    s.add_dependency(%q<bundler>, ["~> 1"])
    s.add_dependency(%q<juwelier>, ["~> 2"])
    s.add_dependency(%q<simplecov>, ["~> 0"])
    s.add_dependency(%q<guard-rspec>, ["~> 0"])
  end
end

